#define KEY_DEBOUNCE_INTERVAL 50

#define DIGIT_TOP 0b00000001
#define DIGIT_MIDDLE 0b01000000
#define DIGIT_BOTTOM 0b00100000
#define DIGIT_LEFT_TOP 0b10000000
#define DIGIT_LEFT_BOTTOM 0b00000010
#define DIGIT_RIGHT_TOP 0b00001000
#define DIGIT_RIGHT_BOTTOM 0b00000100

#define DIGIT_0 DIGIT_TOP | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM
#define DIGIT_1 DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_2 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP;
#define DIGIT_3 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_4 DIGIT_MIDDLE | DIGIT_LEFT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_5 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_6 DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_BOTTOM;
#define DIGIT_7 DIGIT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_8 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_9 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;

#define BLANK_DIGIT 11

//Digit addresses:
#define SCORE_LEFT_BIG 1
#define SCORE_LEFT_SMALL 4
#define SCORE_RIGHT_BIG 0
#define SCORE_RIGHT_SMALL 7
#define PERIOD 2
#define TIME_SECOND_BIG 5
#define TIME_SECOND_SMALL 6
#define TIME_MINUTE_SMALL 3

//Button addresses
#define BUTTON_PIN_LEFT_UP A5
#define BUTTON_PIN_LEFT_DOWN A1
#define BUTTON_PIN_RIGHT_UP A0
#define BUTTON_PIN_RIGHT_DOWN A4
#define BUTTON_PIN_START A3
#define BUTTON_PIN_RESET A2
#define BUTTON_PIN_SHOT_CLOCK 13

#define PIN_DOTS 10
#define PIN_BIG_MINUTE 9

#define PIN_BUZZER 8

// The radio details:
// Our radio's id.  The transmitter will send to this id:
#define RADIO_ID 3
#define RADIO_SEND_INTERVAL 1000
#define PIN_RADIO_CE 12
#define PIN_RADIO_CSN 11
