language: generic
env:
  global:
    - CLI_VERSION=latest
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p $HOME/bin
  - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli core install arduino:avr
install:
  - arduino-cli lib install "NRFLite"
script:
  - arduino-cli compile --verbose --warnings all --fqbn arduino:avr:nano ShotClock
