language: generic
env:
  global:
    - CLI_VERSION=latest
install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mkdir -p $HOME/bin
  - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli core install arduino:avr
  - arduino-cli lib install "NRFLite"
  - arduino-cli lib install "Bounce2"
  - arduino-cli lib install "Chrono"
  - arduino-cli lib install "Adafruit MCP23008 library"
script:
  - arduino-cli compile --fqbn arduino:avr:nano ShotClock
  - arduino-cli compile --fqbn arduino:avr:nano Scoreboard
