#define DIGIT_TOP 0b00000001
#define DIGIT_MIDDLE 0b01000000
#define DIGIT_BOTTOM 0b00100000
#define DIGIT_LEFT_TOP 0b10000000
#define DIGIT_LEFT_BOTTOM 0b00000010
#define DIGIT_RIGHT_TOP 0b00001000
#define DIGIT_RIGHT_BOTTOM 0b00000100

#define DIGIT_0 DIGIT_TOP | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM
#define DIGIT_1 DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_2 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP;
#define DIGIT_3 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_4 DIGIT_MIDDLE | DIGIT_LEFT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_5 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_6 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_BOTTOM;
#define DIGIT_7 DIGIT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_8 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_BOTTOM | DIGIT_LEFT_TOP | DIGIT_LEFT_BOTTOM | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;
#define DIGIT_9 DIGIT_TOP | DIGIT_MIDDLE | DIGIT_LEFT_TOP | DIGIT_RIGHT_TOP | DIGIT_RIGHT_BOTTOM;

